[project]
name = "birdie-hire"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.40.33",
    "fastapi>=0.116.1",
    "pika>=1.3.2",
    "sqlalchemy>=2.0.43",
]
